### ISSUE TITLE
Uploading a corrupt supplemental file prevents processing of other files

### ISSUE THREAD

**Issue by jenlindner** [curationexperts/laevigata#826] opened 2017-11-30 21:40 UTC
https://qa-etd.library.emory.edu/concern/etds/3x816m604?locale=en
and 
https://qa-etd.library.emory.edu/concern/etds/tq57nr01v?locale=en

sun.png is a corrupt file

**Comment by mark-dce** [comment] 2018-07-10 17:21
Let's re-test this against Laevigata 2.x.  If it's still an issue, do the re-mediation below; otherwise, the ticket can be closed with a note that the problem is resolved in 2.x

**ACCEPTANCE**
- [ ] The user is notified in some way of the problem filename
- [ ] There is some kind of operational alert to DCE (could be e-mail, honeybadger, nagios, or splunk)

**Comment by bess** [comment] 2018-07-11 13:04
![corrupt_upload.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46eb9b88319793bdb0fcaf4fab5cf4d665043761260ea62864c7b96aea1a7f02575949f9460e0b17a8fe892ba7e768778c0803bbc3714d36976345f3e5db55ea43a82a994e82bcbd8f4fc1eb3c21e58e8b493e161755.png)

**Comment by bess** [comment] 2018-07-11 13:12
I have been unable to replicate this bug. Even with an extremely corrupt file, no exception is raised.  I do observe an error message in the log file, but because no exception is raised no notifications to honeybadger, nagios etc are triggered. The file as uploaded does not have a preview because imagemagick cannot do anything with it, and it can't be opened because it is corrupt, but it doesn't crash the software in any way. 

See https://qa-upgrade-etd.emory.edu/concern/etds/3n203z22z?locale=en for another example.

**Comment by mark-dce** [comment] 2018-07-11 13:32
Should we close this ticket and open a `future scope` ticket to notify someone when this kind of error is detected and written to the log file?

**Comment by bess** [comment] 2018-07-11 14:48
Good idea. Done. https://github.com/curationexperts/laevigata/issues/1290

**Closed** 2018-07-19 14:51 UTC
Labels: bug, files, release priority, review
