### ISSUE TITLE
in admin --> "Administrative Sets", you can't see all admin sets

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#471] opened 2017-07-12 19:18 UTC

**Comment by mark-dce** [comment] 2017-11-28 22:47
Need to review this after the Hyrax 1.0.5 release and determine if this issue is being caused upstream or in the laevigata codebase.  If it's upstream, consider putting on hold until upgrading to Hyrax 2.x

**Comment by jenlindner** [comment] 2017-12-05 22:27
I looked into this today and don't have enough information to answer that question, but I suspect it's not in Laevigata. It was not fixed by the upgrade, as I still see the problem in my local upgraded code. We create 19 Admin sets, but the solr query that gets generated by Hyrax to get them for the admin index view only returns 10 documents. 

Here's the Laevigata catalog controller search builder default blacklight solr params: 

    config.default_solr_params = {
      qt: "search",
      rows: 10,
      qf: "title_tesim description_tesim creator_tesim keyword_tesim",
      fq: "-has_model_ssim:Collection"
    }

This is the solr query from my server log: 

Solr query: get select {"qt"=>"search", "facet.field"=>["graduation_year_sim", "school_sim", "department_sim", "degree_sim", "submitting_type_sim", "research_field_sim", "generic_type_sim", "committee_names_sim", "keyword_sim"], "facet.query"=>[], "facet.pivot"=>[], "fq"=>["-has_model_ssim:Collection", "", "{!terms f=has_model_ssim}AdminSet"], "hl.fl"=>[], "rows"=>10, "qf"=>"title_tesim description_tesim creator_tesim keyword_tesim", "facet"=>true, "f.graduation_year_sim.facet.limit"=>6, "f.school_sim.facet.limit"=>6, "f.department_sim.facet.limit"=>6, "f.degree_sim.facet.limit"=>6, "f.submitting_type_sim.facet.limit"=>6, "f.research_field_sim.facet.limit"=>6, "f.committee_names_sim.facet.limit"=>6, "f.keyword_sim.facet.limit"=>6, "sort"=>"score desc, system_create_dtsi desc"}

I tried changing the limit of rows to 20 in Laevigata's search builder and then in the Blacklight search builder classes that create the solr query, but couldn't succeed in changing the limit from 10 rows in the solr query (which is strange).

However, I don't know definitely if that's the cause of the problem. Likely possibilities are also the access_controls_to_solr_params and filter_models that are the two final pieces of the parameter_chain that gets assembled by Blacklight. That looks like this: 

[:default_solr_parameters, :add_query_to_solr, :add_facet_fq_to_solr, :add_facetting_to_solr, :add_solr_fields_to_query, :add_paging_to_solr, :add_sorting_to_solr, :add_group_config_to_solr, :add_facet_paging_to_solr, :add_access_controls_to_solr_params, :filter_models]

That's all I've found for now.

**Comment by bess** [comment] 2017-12-06 16:05
Would whoever is looking at this please also look at #846 ?

**Comment by bess** [comment] 2018-07-18 15:21
Fixed in 2.x

**Closed** 2018-07-18 15:21 UTC
Labels: bug, next
