### ISSUE TITLE
Determine if Hyrax provides large file upload support

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#87] opened 2017-04-11 19:27 UTC
Otherwise, add a ticket to develop a solution for large files

Consider https://github.com/carrierwaveuploader/carrierwave

**Comment by shanitajohn** [comment] 2017-06-02 17:59
@jenlindner I think this ticket can be closed because of your work setting up Cloud Providers.

**Comment by shanitajohn** [comment] 2017-06-13 16:30
Jen confirmed that this work was done. Closing this ticket.

**Closed** 2017-06-13 16:30 UTC
