### ISSUE TITLE
Students should be able to edit and update files after submission

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#927] opened 2018-03-19 22:00 UTC
**STORY**
As a student, when my school approver "Requests Changes" from me involving my primary PDF or supplemental files, I should be able to:

**ACCEPTANCE CRITERIA**
- [ ] Delete and replace my primary PDF and resubmit my ETD for review 
- [ ] Delete and replace any one of my supplemental files (without affecting the others) and resubmit my ETD for review 
- [ ] Edit the required metadata for any one of my supplemental files (without affecting the others) and resubmit my ETD for review

**Comment by shanitajohn** [comment] 2018-03-19 22:02
@bess  @mark-dce I created this ticket as a reminder to have a discussion about this work. Fran mentioned it in last Thursday's Hosting Status meeting. My understanding is this works continues to be blocked by Hyrax functionality upstream. Need to ask Val and Jen, too.

**Comment by little9** [comment] 2018-08-02 14:59
This might be a dupe of #1445

**Comment by bess** [comment] 2018-08-03 19:23
Duplicate.

**Closed by bess** 2018-08-03 19:23 UTC
Labels: UI, backend, backlog, files, on deck
