### ISSUE TITLE
designate primary research field in about my etd

### ISSUE THREAD

**Issue by jenlindner** [curationexperts/laevigata#402] opened 2017-06-29 00:13 UTC
See #188

**ACCEPTANCE CRITERIA**
- [ ] Since I can add up to 3 research fields, I would like a way to see which field I have designated as my primary research field

**Comment by shanitajohn** [comment] 2017-06-29 19:28
Closing this ticket. Duplicate of #365

**Comment by shanitajohn** [comment] 2017-06-29 19:28
Closing this ticket. Duplicate of #365

**Closed by shanitajohn** 2017-06-29 19:28 UTC
Labels: ready, UI
